trixi-framework/libtrixi

examples/simple_trixi_controller.c, src/trixi.c, src/trixi.h
If inside a `libtrixi/build` directory and after compiling libtrixi and the examples, this PR allows one to run a simulation with
```shell
examples/simple_trixi_controller ../LibTrixi.jl/ ../LibTrixi.jl/examples/libelixir_demo.jl
```
giving output similar to this
```
Activating project at `/mnt/ssd/home/mschlott/hackathon/libtrixi/LibTrixi.jl`
Project LibTrixi v0.1.0
Status `/mnt/ssd/home/mschlott/hackathon/libtrixi/LibTrixi.jl/Project.toml` (empty project)
Module LibTrixi.jl loaded
Simulation state initialized
Current time step length: 0.300000
Current time: 0.3
Current time: 0.6
Current time: 0.8999999999999999
Current time: 1.0
Final time reached
Simulation state finalized
libtrixi: finalize
```
I created this as a PR into #14, feel free if you're happy with this.
=> Allow passing project_dir and libelixir path to libtrixi

src/trixi.c
=> Store function pointers in library

.github/dependabot.yml, .github/workflows/ci.yml, .gitignore, README.md, docs/src/index.md
=> Add initial CI testing capabilities

.github/workflows/ci.yml, README.md, docs/src/index.md, examples/CMakeLists.txt, examples/fortran_hello_world.f90, examples/simple_trixi_controller.c, examples/simple_trixi_controller.f90, src/trixi.f90
Resolves #15 (I believe).
This PR creates a `simple_trixi_controller.f90` that mimics the C version `simple_trixi_controller.c` nearly identically. It also makes the Fortran interface match the current C interface again.
C version:
```
$ examples/simple_trixi_controller_c ../run ../run/libelixir_demo.jl
Activating project at `/mnt/ssd/home/mschlott/hackathon/libtrixi/run`
Status `/mnt/ssd/home/mschlott/hackathon/libtrixi/run/Project.toml`
[7e097bd5] LibTrixi v0.1.0 `../LibTrixi.jl`
Module LibTrixi.jl loaded
Simulation state initialized
Current time step length: 0.300000
Current time: 0.3
Current time: 0.6
Current time: 0.8999999999999999
Current time: 1.0
Final time reached
Simulation state finalized
libtrixi: finalize
```
Fortran version:
```
$ examples/simple_trixi_controller_f ../run …
```
=> Add Fortran example to match C example

.github/workflows/ci.yml, utils/libtrixi-init-julia
Otherwise we get weird startup errors when calling `MPI.Init()` from Trixi.jl, since HDF5.jl pulls in OpenMPI from OpenMPI_jll.jl (via HDF5_jll.jl), which causes all kinds of errors upon initializing MPI.
=> Use system HDF5 library

.github/workflows/ci.yml, .gitignore, CMakeLists.txt, README.md, docs/src/index.md, examples/CMakeLists.txt, examples/MakefileExternal, src/trixi.c, src/trixi_tls.c
=> Allow one to use `JULIA_DEFINE_FAST_TLS` by linking to `libtrixi_tls.o`

examples/simple_trixi_controller.f90, src/trixi.f90
I noticed in MESSy that the current Fortran bindings might be hard to use for people not familiar with C-style programming or calling C functions from Fortran. Specifically, the use of `trim(adjustl(string)) // c_null_char` for string arguments such as
```fortran
CALL trixi_initialize(TRIM(ADJUSTL(trixi_runtime_path))//char(0))
```
([source](https://gitlab.dkrz.de/MESSy/MESSy/-/blob/52a431eaa5001eb88365d375f5b1d52503dd7ae2/messy/smcl/messy_trixi.f90#L68)) or the awkward comparison of boolean-intent return values against `0`/`1` such as
```fortran
IF (trixi_is_finished(handle) .ne. 0) THEN
```
([source](https://gitlab.dkrz.de/MESSy/MESSy/-/blob/52a431eaa5001eb88365d375f5b1d52503dd7ae2/messy/smcl/messy_trixi.f90#L105)).
This PR changes the Fortran bindings to our C API such that all …
=> Provide convenience methods for Fortran interface

README.md, docs/src/index.md, examples/simple_trixi_controller.c, src/trixi.c, src/trixi.f90, src/trixi.h, utils/libtrixi-init-julia
Before, one always had to start programs with `JULIA_DEPOT_PATH=path myprog` when running a program `myprog` that links to `libtrixi`. With this PR, setting `JULIA_DEPOT_PATH` becomes unnecessary as long as the default depot location used by by `utils/libtrixi-init-julia` is left untouched.
This should help to avoid user errors in case they forget to set the Julia depot path appropriately. If a `JULIA_DEPOT_PATH` environment variable is set, it will honored, thus the user can still provide non-standard locations via the environment. Overriding the default is also possible by calling `trixi_initialize` with a second, non-null argument.
=> Simplify usage by allow to omit the JULIA_DEPOT_PATH

examples/simple_trixi_controller.c, src/trixi.c, utils/libtrixi-init-julia
Hotfix, that hopefully can be removed again later.
https://github.com/JuliaParallel/MPI.jl/issues/746
=> Work around MPI_set_attr error

.github/workflows/ci.yml, README.md, docs/src/index.md, utils/libtrixi-init-julia
=> Adapt to t8code

CMakeLists.txt, examples/CMakeLists.txt
When mpi does not reside in a default location, cmake's `FindCMake` module might still find it and will add `-lmpi` as a library to link. However, if neither `LD_LIBRARY_PATH` nor some other mechanism includes the location, the actual linking fails. `MPI_C_LINK_FLAGS` contains the required directory, but is currently not used. 
Since we meanwhile require cmake version 3.9, we can use the imported target, which magically solves the issue.
=> Use imported target for MPI

LibTrixi.jl/Project.toml, LibTrixi.jl/src/LibTrixi.jl, src/trixi.c
As worked out here:
https://github.com/JuliaParallel/MPI.jl/issues/746
=> Canonical fix for MPI attr error

CMakeLists.txt, examples/CMakeLists.txt
Resolves #70.
Note that we cannot add `-Wpedantic` since we convert the return value of `jl_unbox_voidpointer` to a function pointer when we want to call Julia functions from C. While this does not present an issue on x64 platforms, it is technically undefined behavior (C only explicitly allows object pointer to object pointer conversion, and function pointer to function pointer conversion). There does not seem to be a sane way around this at the moment, but since it is not presenting a problem either, I think it is ok for now.
=> Add `-Wall -Wextra -Werror` to compilation flags

.github/dependabot.yml
Similar to what we have done in other repos, this should keep the noise created by the alerts in check.
=> Switch to monthly dependabot alerts

CMakeLists.txt, README.md, docs/src/index.md, src/auxiliary.c
=> Specify C11 and Fortran 2018 language standards

src/api.c, src/api.f90, test/interface_c.cpp
=> Safeguard `trixi_initialize`/`trixi_finalize` against erroneous use

.github/workflows/ci.yml
This PR combines various small CI improvements that hopefully make it easier to understand or adapt the main CI testing config file. Since a lot in the file has changed, I recommend for a review to either directly read the entire new file and not look at the diff, or to just step through all commit diffs manually to understand the changes that have been performed.
Here's a summary of the main modifications:
* Throw out unused configurations (Windows, macOS, Valgrind)
* Enable caching of t8code installation (to save ~3 minutes)
* Simplify the job configuration by using a simpler matrix
* Execute Google Tests also in 'regular' runs
Some of the changes might be too far reaching, so feel free to comment/question these choices.
=> Miscellaneous CI improvements

.github/workflows/ci.yml, utils/libtrixi-init-julia
HDF5 0.17.0 has arrived and we have to switch to using `set_preferences`.
=> Use set_preferences to set system hdf5

.github/workflows/TagBot.yml, Project.toml, docs/src/developers.md
With https://github.com/JuliaRegistries/TagBot/pull/279 merged, we need to wait for a new version of the TagBot action to be tagged (no pun intended). Once this has happened, we should be able to use TagBot for automatic new release creation.
=> Make TagBot work again (at all)

LibTrixi.jl/src/LibTrixi.jl, LibTrixi.jl/src/api_c.jl
It was an oversight of myself to fill the version info arrays at *runtime* instead of *compile time*. Since the module gets recompiled whenever one of its (transitive) dependencies changes, this should always be up-to-date anyways.
This change hopefully fixes some issues encountered when trying to build libtrixi with PackageCompiler.jl.
=> Store version info at compile time

CMakeLists.txt
At the moment it is not needed.
=> Remove linking of MPI for libtrixi.so

.github/workflows/ci.yml
Got the token from https://app.codecov.io/gh/trixi-framework/libtrixi/settings
and followed https://github.com/codecov/codecov-action?tab=readme-ov-file#usage
=> Update codecov to v4 and add token

LibTrixi.jl/examples/libelixir_tree2d_warm_bubble.jl
=> Add Bryan/Fritsch warm bubble test case

LibTrixi.jl/examples/libelixir_p4est3d_euler_baroclinic_instability.jl
=> Add baroclinic instability test case

.github/workflows/TagBot.yml
TagBot can be instructed to leave out certain commit messages when compiling the changelog based on labels.
I think we do not need all the "bump x" messages.
CompatHelper messages, however, will not be captured as they do not have a label.
=> Filter dependabot commits in release changelog

.github/workflows/SpellCheck.yml, .github/workflows/ci.yml, LibTrixi.jl/Project.toml, LibTrixi.jl/src/api_jl.jl, utils/libtrixi-init-julia
=> Swap installation order of Trixi.jl and LibTrixi.jl

.github/workflows/ci.yml
This fixes the long lasting package compiler issue. Not because of julia versions, but because of a new package compiler release. In particular this PR https://github.com/JuliaLang/PackageCompiler.jl/pull/987 and this line https://github.com/JuliaLang/PackageCompiler.jl/pull/987/files#diff-ec15186e80d0dd77de71866cee17c75857c4eb441c51df407b96f680c11cf847 seem relevant. 
However, I noticed that the resulting shared object is now large (~700 MB) regardless of whether `filter_stdlibs` is set to true or false.
If we merge this and thereby drop julia 1.9, this resolves #152 #213
=> Use main julia version for PackageCompiler

LibTrixi.jl/Project.toml, LibTrixi.jl/examples/libelixir_p4est2d_euler_sedov.jl, LibTrixi.jl/test/Project.toml
Closes #245 
Closes #246
Explicitly set wave speed for Local Lax-Friedrichs to `max_abs_speed_naive` as it used to be.
Xref: https://github.com/trixi-framework/Trixi.jl/pull/2458
=> Add  Trixi version 0.13

.github/workflows/SpellCheck.yml, LibTrixi.jl/Project.toml, LibTrixi.jl/examples/libelixir_p4est2d_euler_sedov.jl, LibTrixi.jl/examples/libelixir_t8code3d_euler_baroclinic_instability.jl, LibTrixi.jl/examples/libelixir_t8code3d_euler_tracer.jl, LibTrixi.jl/lib/Project.toml, LibTrixi.jl/lib/build.jl, LibTrixi.jl/test/Project.toml
~~Add `PreallocationTools = "< 0.4.30"` compat.~~
Use `filter_stdlibs = false` (thanks to @vchuravy )
(we found in #216 that the resulting shared object is large anyways)
Resolves #253 
Use `Trixi.False() ` instead of `OrdinaryDiffEq.False()`.
=> Fix package compiler and regular builds
