trixi-framework/libtrixi

- .gitignore
- README.md
- docs/src/index.md
- utils/libtrixi-init-julia
> Set up Julia configuration for libtrixi

- CMakeLists.txt
> Install `LibTrixi.jl` to `${PREFIX}/share/libtrixi/LibTrixi.jl`

- .github/workflows/ci.yml
- LibTrixi.jl/src/LibTrixi.jl
- LibTrixi.jl/src/api_jl.jl
- README.md
- docs/src/index.md
- src/trixi.c
> Add ability to control debug output via `LIBTRIXI_DEBUG`

- CMakeLists.txt
> Install modfiles to include/ dir

- .github/workflows/ci.yml
- README.md
- docs/src/index.md
- examples/.gitignore
- examples/MakefileExternal
Resolves #4.
Needs #36 to be merged first.
> Add simple example for building an external project against libtrixi

- LibTrixi.jl/src/api_jl.jl
> Fix call of invokelatest for julia 1.8

- examples/CMakeLists.txt
This should make it easier to quickly add new examples for (local) testing.
> Generalize examples cmake file

- README.md
- docs/src/index.md
Based on https://github.com/trixi-framework/trixi-framework.github.io/pull/23#discussion_r1259665271.
> Clarify development state in README

- CMakeLists.txt
- docs/doxygen/Doxyfile
- examples/simple_trixi_controller.c
- examples/simple_trixi_controller.f90
- src/trixi.f90
- src/trixi.h
- src/trixi_version.c
> Add version API

- README.md
- examples/CMakeLists.txt
- examples/simple_trixi_controller.jl
- utils/libtrixi-init-julia
I would like to have `simple_trixi_controller.jl` installed as well (and get the instructions in README.md right). It is however not really `bin/`.
> Update julia controller example

- .github/workflows/ci.yml
- test/c/interface_c.cpp
- test/fortran/versionInfo_suite.f90
Compare version only up to `-<pre-release>`
> Fix version test

- CITATION.bib
- README.md
- docs/src/index.md
> Add DOI and referencing information to the docs

- LibTrixi.jl/src/LibTrixi.jl
> Restore Julia 1.8 compatability for package filtering

- docs/doxygen/Doxyfile
> Fix input files for Doxygen documentation

- .github/workflows/ci.yml
Fixes #136
See https://github.com/actions/runner-images/issues/5470
> Update apt-get before apt-get install

- examples/trixi_controller_data.f90
Add nullify after deallocation.
> Small update in trixi_controller_data_f

- README.md
- docs/src/index.md
- remove warning of libtrixi being in an early stage
- add cmake t8code option
> Small documentation update

- .github/workflows/ci.yml
> Do not run CI workflow for changes in docs

- LibTrixi.jl/test/Project.toml
> Match compat bounds for Trixi.jl in LibTrixi.jl and LibTrixi.jl/test

- .github/workflows/SpellCheck.yml
- LibTrixi.jl/Project.toml
- LibTrixi.jl/test/Project.toml
- docs/src/developers.md
- src/api.f90
> Bump compat for Trixi to version 0.12
